export const SET_CART_ITEMS = 'SET_CART_ITEMS';
export const REMOVE_CART_IETMS = 'REMOVE_CART_IETMS';

export const FETCH_ORDER_REQUEST = 'FETCH_ORDER_REQUEST';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAILURE = 'FETCH_ORDER_FAILURE';