export const CHANGE_ACTIVE_CATEGORY = 'CHANGE_ACTIVE_CATEGORY';

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUEST';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE';

export const FETCH_MORE_ITEMS_REQUEST = 'FETCH_MORE_ITEMS_REQUEST';
export const FETCH_MORE_ITEMS_SUCCESS = 'FETCH_MORE_ITEMS_SUCCESS';
export const FETCH_MORE_ITEMS_FAILURE = 'FETCH_MORE_ITEMS_FAILURE';

export const FETCH_SEARCH_ITEMS_REQUEST = 'FETCH_SEARCH_ITEMS_REQUEST';
export const FETCH_SEARCH_ITEMS_SUCCESS = 'FETCH_SEARCH_ITEMS_SUCCESS';
export const FETCH_SEARCH_ITEMS_FAILURE = 'FETCH_SEARCH_ITEMS_FAILURE';

export const SET_SEARCH = 'SET_SEARCH';