export const FETCH_ITEM_REQUEST = 'FETCH_ITEM_REQUEST';
export const FETCH_ITEM_SUCCESS = 'FETCH_ITEM_SUCCESS';
export const FETCH_ITEM_FAILURE = 'FETCH_ITEM_FAILURE';

export const CHANGE_SIZE_ITEM = 'CHANGE_SIZE_ITEM';
export const CHANGE_COUNT_ITEM = 'CHANGE_COUNT_ITEM';